# Generated by Django 3.2.4 on 2021-06-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20210624_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, '남성'), (1, '여성'), (2, '숨기기')], default=3),
        ),
    ]
