# Generated by Django 3.2 on 2021-06-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('kwh', models.FloatField(verbose_name='kWh')),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
