# Generated by Django 3.2.4 on 2021-06-30 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='item',
        ),
    ]
